version: "2"

services:
  gangway:
    image: golang:1.6.1-alpine
    volumes:
      - .:/go/src/github.com/bobbytables/gangway
    command: ["go", "run", "cmd/gangway/main.go", "start", "--addr=0.0.0.0:8080"]
    working_dir: /go/src/github.com/bobbytables/gangway
    ports:
      - 8080:8080
